# Use postgres/example user/password credentials
version: '3.1'

services:

  postgreSQL:
    image: postgres:latest
    restart: always
    environment:
    ports:
      - "5432"
      POSTGRES_PASSWORD: dra19
